services:
  service:
    image: ghcr.io/luiseont/lineraodds-service:latest
    container_name: service
    ports:
      - "127.0.0.1:8081:8081"
    volumes:
      - .:/build
      - service-wallet:/root/.config/linera
      - shared-env:/shared
    #environment:
    # - FORCE_REDEPLOY=true  # Forzar redespliegue del contrato
    entrypoint: ["bash", "/build/service/run.bash"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1200s

  front:
    image: ghcr.io/luiseont/lineraodds-front:latest
    container_name: front
    volumes:
      - ./front:/front
      - shared-env:/shared
    entrypoint: ["bash", "/front/build-prod.bash"]
    restart: unless-stopped  # Mantener el contenedor activo
    depends_on:
      service:
        condition: service_started  # Solo esperar que inicie, no que esté healthy

  oracle:
    image: ghcr.io/luiseont/lineraodds-oracle:latest
    container_name: oracle
    ports:
      - "127.0.0.1:9999:9999"
      - "127.0.0.1:8090:8090"
    volumes:
      - ./oracle:/oracle
      - linera-wallet:/root/.config/linera
      - shared-env:/shared
    environment:
      - LINERA_FAUCET=https://faucet.testnet-conway.linera.net
      - SERVICE_URL=http://localhost:8090
      - API=https://v3.football.api-sports.io
      - API_KEY=${API_KEY}
      - DEMO_MODE=true
      - LEADERBOARD_ENABLED=true
      - LEADERBOARD_PRIZE_POOL=10000
    restart: unless-stopped
    entrypoint: ["bash", "/oracle/start-prod.bash"]
    depends_on:
      service:
        condition: service_healthy

volumes:
  service-wallet:
  linera-wallet:
  shared-env: