services:
  service:
    build: ./service
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
    - "8081:8081" # service main
    volumes:
    - .:/build
    - shared-env:/shared
    environment:
      - FORCE_REDEPLOY=true  # Forzar redespliegue del contrato
    entrypoint: ["bash", "/build/service/run.bash"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1200s
  front:
    build: ./front
    ports:
    - "5173:5173"
    volumes:
    - ./front:/front
    - shared-env:/shared
    entrypoint: ["bash", "/front/start.bash"]
    depends_on:
      service:
        condition: service_healthy
  oracle:
    build: ./oracle
    ports:
      - "127.0.0.1:9999:9999"
      - "127.0.0.1:8090:8090"
    volumes:
      - ./oracle:/oracle
      - linera-wallet:/root/.config/linera
      - shared-env:/shared
    environment:
      - LINERA_FAUCET=https://faucet.testnet-conway.linera.net
      - SERVICE_URL=http://localhost:8090
      - API=https://v3.football.api-sports.io
      - API_KEY=0ea8f6e37f0d7f34b36f300b31afd19c
      - DEMO_MODE=true
      - LEADERBOARD_ENABLED=true
      - LEADERBOARD_PRIZE_POOL=10000
    restart: unless-stopped
    entrypoint: ["bash", "/oracle/start.bash"]
    depends_on:
      service:
        condition: service_healthy
volumes:
  linera-wallet:
  shared-env:
